### ISSUE TITLE
[Feature?]: Javascript tokens containing CSS Properties

### ISSUE THREAD

**Issue by josh-degraw** [pluralsight/tva#158]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It might be a good idea, for the sake of trying to keep a single source of truth, to expose a package of JS variables with the values being the CSS properties themselves, e.g.

```js
const psNeutralBorder = 'var(--ps-neutral-border)'
```

That way you could get the benefits of both CSS-in-JS and pure CSS solutions.

### Examples 🌈

A full-featured system that uses this method is [vanilla-extract](https://vanilla-extract.style/).

### Motivation 🔦

I've been working on trying and integrating this library with the Skills Management Design System and my team's codebase, which has a mixture of `PSDS` and `SMDS` components, and I'm getting the feeling that we can better future-proof the `SMDS` by deferring to external variables for the theme tokens when possible.

**Comment by caseybaggz** [comment]
@josh-degraw thanks so much for this topic. Since this is more of a discussion - to ensure we are following our [guidelines](https://design.pluralsight.com/docs/development/getting-started/support#github), I'm going to go ahead and close this and convert it to a discussion.

From there, if there is enough support from the community, we will convert it back into an issue. 👍
